services:
  backend:
    build:
      context: .                     # ważne: kontekst to root projektu
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend       # live-reload w dev
    restart: unless-stopped

  frontend:
    build:
      context: .                      # kontekst root, stąd Dockerfile znajdzie requirements.txt
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend      # live-reload w dev
    restart: unless-stopped